### ISSUE TITLE
微信需要特殊处理：web和服务号使用union id时应保存为1个user的2个social accounts

### ISSUE THREAD

**Issue by FishWade** [sinkcup/laravel-make-auth-socialite#8]

**Comment by sinkcup** [comment]
这个不通用，是因为微信技术差，开放平台混乱，导致的。做成补丁即可：

https://gist.github.com/sinkcup/76ba56374e9442caa270c789d3178c83

**Comment by sinkcup** [comment]
![image](https://user-images.githubusercontent.com/4971414/56465412-3233b200-642f-11e9-98dc-af5d2caf2165.png)
![image](https://user-images.githubusercontent.com/4971414/56465434-6d35e580-642f-11e9-80aa-db783f1325c7.png)
![image](https://user-images.githubusercontent.com/4971414/56465469-52b03c00-6430-11e9-9579-a3529850736e.png)
![image](https://user-images.githubusercontent.com/4971414/56465491-d702bf00-6430-11e9-931e-283b7fcf01c8.png)
![image](https://user-images.githubusercontent.com/4971414/56465549-e2a2b580-6431-11e9-82f6-adb92579392a.png)

![image](https://user-images.githubusercontent.com/4971414/56465519-6314e680-6431-11e9-8fdd-227aa36f7aa1.png)
![image](https://user-images.githubusercontent.com/4971414/56465532-99526600-6431-11e9-81cf-07c1f3625aa4.png)

**Comment by sinkcup** [comment]
![image](https://user-images.githubusercontent.com/4971414/56465610-7b860080-6433-11e9-8345-55534389a6dc.png)
![image](https://user-images.githubusercontent.com/4971414/56465636-d1f33f00-6433-11e9-97ac-e1ed8a51949d.png)
